### ISSUE TITLE
uuidForInstallation persists after reinstall

### ISSUE THREAD

**Issue by mmahkamov** [fabiocaccamo/FCUUID#12]
Not sure if I'm getting it right but based on the persistence table, the uuidForInstallation is expected to be removed when the app is uninstalled. However, that's not the case (tested on iOS 9 and 10). Probably because of the following line:

`_uuidForInstallation = [self _getOrCreateValueForKey:_uuidForInstallationKey defaultValue:nil userDefaults:YES keychain:YES service:nil accessGroup:nil synchronizable:NO];`

I believe keychain argument should be NO here.

**Comment by fabiocaccamo** [comment]
You're right, sorry for the mistake.
Now it's fixed with `1.3.1` version.

**Comment by mmahkamov** [comment]
Thanks for the fix!
