### ISSUE TITLE
iOS 10.3 deletes keychain items when an app is deleted. 

### ISSUE THREAD

**Issue by cielpy** [fabiocaccamo/FCUUID#14]
https://twitter.com/ericshapiro/status/833685944477818882

**Comment by itruf** [comment]
I'm interested in sollution of this problem too.

I have few apps with unique id stored in keychain. I hope that we can find way to solve this together.

**Comment by fabiocaccamo** [comment]
https://twitter.com/andreipop/status/839069694980210692

**Comment by jackyzh** [comment]
I just tried in iOS 10.3 beta 7, it works as before. it seems like a bug in previous beta release.

**Comment by fabiocaccamo** [comment]
@jackyzh thanks for your feedback, probably it was just a bug. 
Anyway I leave this issue open for now.
Any other user's feedback would be appreciated.
