### ISSUE TITLE
Carthage support ?

### ISSUE THREAD

**Issue by Vinzius** [fabiocaccamo/FCUUID#18]
Hi Team,

First, thanks for the work!

Would you consider an update if I do a PR with [Carthage](https://github.com/Carthage/Carthage) support?

Cheers,
Vincent

**Comment by fabiocaccamo** [comment]
Thanks!
Any improvement is appreciated :)

**Comment by Vinzius** [comment]
Ok, I'll try to submit one soon :-)
Thanks for the fast reply.

**Comment by fabiocaccamo** [comment]
Frankly, I never used Carthage and I'm not working on iOS right now.
I would not create another branch, but I would just specify in the documentation that with iOS8+ it possible to install the lib using cartage, is it possible?

**Comment by Vinzius** [comment]
In order to use Carthage, you need to have schemes (so an xcodeproj) (details [here](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)).

For the iOS8 requirement, it's because of the dynamic frameworks.

I understand you don't really want to complicate the architecture of this library. Thus I'll probably just do a manual installation or fork the project (I stop using Cocoapods).

That being said, I'm not sure what is required to support swift package manager, but I think it would be a nice addition to the project.
