### ISSUE TITLE
uuidForDevice

### ISSUE THREAD

**Issue by zero1222** [fabiocaccamo/FCUUID#19]
When i want to get uuid after the system is reinstalled, i must log in to iCloud ?

**Comment by fabiocaccamo** [comment]
If you mean uuidForDevice, that isn't always possible. 
You can do it only if the user restores a device backup which includes also keychain's data.
Check [this table](https://github.com/fabiocaccamo/FCUUID#persistence) for more info about uuid(s) persistency.

**Comment by zero1222** [comment]
Thank you so much
