### ISSUE TITLE
Same ID ,two devices

### ISSUE THREAD

**Issue by zero1222** [fabiocaccamo/FCUUID#20]
Why is the ID generated by the two devices the same?

**Comment by fabiocaccamo** [comment]
@zero1222 the two devices are of the same user?

**Comment by fabiocaccamo** [comment]
@rojo69 exactly, this could benthe only one reason.

**Comment by rojo69** [comment]
Have you considered moving the storage from NSUserDefaults to a file with the property NSURLIsExcludedFromBackupKey set?
