### ISSUE TITLE
same ID，one iphone ，two UDID

### ISSUE THREAD

**Issue by tangbing** [fabiocaccamo/FCUUID#21]
I use FCUUID as `NSString *deviceUUID = [FCUUID uuidForDevice];`，but` same ID，one iphone ，two UDID，log is  NSUbiquitousKeyValueStore error: com.xxx.xxx has no valid com.apple.developer.ubiquity-kvstore-identifier entitlement，can you help me?

**Comment by zero1222** [comment]
Is it possible to generate the same ID in two different applications?

**Comment by fabiocaccamo** [comment]
@zero1222 actually it is not possible, this could be a new feature.
