### ISSUE TITLE
Same device, different signature,got different id?

### ISSUE THREAD

**Issue by tianguanghui** [fabiocaccamo/FCUUID#23]
Same device, different signature,got different id?
[FCUUID uuidForDevice]

**Comment by fabiocaccamo** [comment]
If you want the same `uuidForDevice` your apps must have **KeyChain sharing** enabled and app identifiers must have the **same bundle seed**.

https://github.com/fabiocaccamo/FCUUID#how-can-i-share-the-device-uuid-between-two-apps
