### ISSUE TITLE
Can I continue use this on iOS 14.5？

### ISSUE THREAD

**Issue by Nododo** [fabiocaccamo/FCUUID#28]
whether this library is limited on iOS 14.5?

thanks !

**Comment by fabiocaccamo** [comment]
@Nododo frankly I have not tested it on the latest iOS versions, if you have any problem let me know.

**Comment by xiangBiaoOne** [comment]
> @Nododo frankly I have not tested it on iOS 14.5, if you have any problem let me know.

I tried. No problem

**Comment by fabiocaccamo** [comment]
@xiangBiaoOne thank you!
