### ISSUE TITLE
Same device id for same iCloud account

### ISSUE THREAD

**Issue by jigarinspiron** [fabiocaccamo/FCUUID#29]
- I need unique id for my project so I have used this framework but then I realise it returns same user device id for same iCloud account

**Comment by fabiocaccamo** [comment]
@jigarinspiron I don't understand the problem, could you explain better your expectations and what is happening instead?

**Comment by fabiocaccamo** [comment]
@jigarinspiron feel free to re-open this issue providing more useful informations.
