### ISSUE TITLE
_uuidForDevice starts to return the same UUID for different devices (issue probably started around iOS 16.6.1)

### ISSUE THREAD

**Issue by duxthefux** [fabiocaccamo/FCUUID#39]
Hi,

we're currently seeing the case where 2 different iPads, which use the same apple ID would generate the same UUID, which is obviously not what one wants.

We don't know for sure, but it seems it all started with around iOS ~16.6.1.

Is anybody else seeing this, or even knows a fix for it?

Thanks a lot!

**Comment by fabiocaccamo** [comment]
@duxthefux I think that in this case the UUID has been synced between the devices via the keychain: 
https://github.com/fabiocaccamo/FCUUID#persistence

**Comment by duxthefux** [comment]
@fabiocaccamo We found the issue on the weekend. It was because some users restored an iCloud backup from device A on device B and kept using device A and B at the same time. The local keychain obviously is also restored in this case.

Good to close it, as it's not a library issue.

Thanks!

Maybe this thread helps people you run into something similar.

**Comment by fabiocaccamo** [comment]
@duxthefux thank you for having provided more informations, this will be surely useful to someone else! 

Could you give a look to #30?
