### ISSUE TITLE
同一个设备登录多个appid,同步了keychain信息的话

### ISSUE THREAD

**Issue by SunXia9288** [fabiocaccamo/FCUUID#40]
同一个设备登录多个appid,同步了keychain信息的话，会导致获取的uuid发生变化吗？会被新的appid中的keychain信息覆盖掉？

**Comment by fabiocaccamo** [comment]
@SunXia9288 write in english please.

**Comment by SunXia9288** [comment]
If you log in to multiple Appids on the same device and synchronize keychain information, does the obtained uuid change? Will the keychain information in the new appid be overwritten?

**Comment by fabiocaccamo** [comment]
@SunXia9288 different AppIDs will have different uuid(s).

**Comment by SunXia9288** [comment]
Thank you very much for your answer
If keychain sharing is not enabled, the uuiddevice occasionally changes during uninstallation and reinstallation. What is the cause

**Comment by fabiocaccamo** [comment]
Strange, are you sure that it's uninstallation / reinstallation and not restore from backup?
