### ISSUE TITLE
iCloud Keychain Syn

### ISSUE THREAD

**Issue by jfcadillo951** [fabiocaccamo/FCUUID#6]
What Happens if iCloud is Sync Keychain and try to get device ID on 2 devices with same iCloud account.

**Comment by fabiocaccamo** [comment]
You will obtain the same device ID.

**Comment by jfcadillo951** [comment]
How about put on UICKeyChainStore synchronizable false, it will fixes this?

**Comment by fabiocaccamo** [comment]
The `uuidsOfUserDevices` method needs a synchronizable keychain, so I think that the only one solution would be to store `uuidForDevice` and `uuidsOfUserDevices` on two different keychain instances (the first one **not synchronizable** and the second one synchronizable).

**Comment by fabiocaccamo** [comment]
UPDATE: by default keychain items are not synchronizable, so you will not obtain the same device ID.
I'm going to release 1.2.0 version where:
- `uuidForDevice` **(not synchronizable)**
- `uuidsOfUserDevices` **(synchronizable)**

**Comment by fabiocaccamo** [comment]
I just released 1.2.0 version.
