### ISSUE TITLE
How can I share the same UUID between two app ?

### ISSUE THREAD

**Issue by BeanDu** [fabiocaccamo/FCUUID#8]

**Comment by fabiocaccamo** [comment]
https://github.com/fabiocaccamo/FCUUID#requirements--dependencies

**Comment by Zkim** [comment]
Hey, how did you solve the problem? Can you please share? Two app UUID is difference

**Comment by fabiocaccamo** [comment]
Your apps identifiers must have the same bundle seed and KeyChain sharing enabled.

**Comment by Zkim** [comment]
thanks
