### ISSUE TITLE
Crash on uuid for device

### ISSUE THREAD

**Issue by hamdullahshah** [fabiocaccamo/FCUUID#9]
"uuidForDeviceInMemory" is nil and calling "isEqualToString" on it causing crash.

[line number in code](https://github.com/fabiocaccamo/FCUUID/blob/master/FCUUID/FCUUID.m#L160)

![screen shot 2016-03-02 at 9 54 21 am](https://cloud.githubusercontent.com/assets/1726321/13448343/4aa57796-e05d-11e5-8dc5-cb0adc0c9019.png)

EDIT:

So here the scenario to generate
Use the UUIDForDevice, and then delete the app and reinstall it again,

**Comment by fabiocaccamo** [comment]
I fixed it and I'm going to release 1.2.0 version.

**Comment by hamdullahshah** [comment]
Is it the correct way to fix ? https://github.com/fabiocaccamo/FCUUID/pull/10

**Comment by fabiocaccamo** [comment]
Yes, it's correct, but I will not merge your PR because in the next version I did some code refactoring and fixed this bug differently. Thanks anyway! :)

**Comment by icoco** [comment]
looks need identify which app used ... like code below 

NSString* _deviceKeyGenerate(NSString* suffix){
    NSBundle* bundle = [NSBundle mainBundle];
    NSString* identifier = [bundle objectForInfoDictionaryKey:@"CFBundleIdentifier"];
    return [NSString stringWithFormat:@"%@-%@",identifier,suffix];
}


#define _uuidForInstallationKey   _deviceKeyGenerate(@"i")
#define _uuidForDeviceKey   _deviceKeyGenerate(@"d")
#define _uuidsOfUserDevicesKey   _deviceKeyGenerate(@"u")
#define _uuidsOfUserDevicesToggleKey   _deviceKeyGenerate(@"t")

**Comment by fabiocaccamo** [comment]
Just released 1.2.0 pod, check it.

**Comment by fabiocaccamo** [comment]
@icoco it's an interesting request, open another issue please.
